name: Daily Playwright Run

on:
  schedule:
    - cron: '5 10 * * *'   # 3:30 PM IST every day

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: npm ci
      - run: npx playwright install
      - run: npx playwright test
